// <auto-generated />
// Hand-authored model snapshot stub for the initial migration. EF Core's
// migrations infrastructure expects a snapshot class beside the migration
// classes; the design-time tooling will regenerate this file when the
// orchestrator runs `dotnet ef migrations add` for follow-up migrations.
// Until then this stub is enough to satisfy the migrations pipeline at
// `dotnet ef database update` time, because the migration class itself
// holds the full Up/Down. Future migrations will overwrite this file.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ShopFlow.Inventory.Infrastructure;

#nullable disable

namespace ShopFlow.Inventory.Infrastructure.Migrations;

[DbContext(typeof(InventoryDbContext))]
internal partial class InventoryDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        // Intentionally empty in the bootstrap commit. The migration's
        // Up/Down methods carry the full schema; EF Core regenerates this
        // snapshot the next time `dotnet ef migrations add` runs.
        modelBuilder.HasAnnotation("ProductVersion", "8.0.10");
    }
}
