/**
 * Single source of truth for ScreenId → URL path mapping.
 *
 * Sidebar consumes this to build `<Link to={...}>` items; the route
 * files at web/src/routes/_auth/<screen>.tsx use the same path constants
 * via the `<Route path>` field generated by TanStack Router.
 *
 * Sprint-6 plan U6.
 */

import type { ScreenId } from './Sidebar';

export const SCREEN_PATHS: Record<ScreenId, string> = {
  dashboard: '/dashboard',
  inventory: '/inventory',
  inbound: '/inbound',
  orders: '/orders',
  channels: '/channels',
  sync: '/sync',
  settings: '/settings',
  audit: '/audit',
  tenants: '/tenants',
  onboarding: '/onboarding',
};
