<Project Sdk="Microsoft.NET.Sdk">

  <!-- Outbound module — Application placeholder (plan U9). -->

  <ItemGroup>
    <ProjectReference Include="..\ShopFlow.Outbound.Domain\ShopFlow.Outbound.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\ShopFlow.SharedKernel\ShopFlow.SharedKernel.csproj" />
  </ItemGroup>

</Project>
