/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MfaEnrollRouteImport } from './routes/mfa/enroll'
import { Route as MfaChallengeRouteImport } from './routes/mfa/challenge'
import { Route as AuthTenantsRouteImport } from './routes/_auth/tenants'
import { Route as AuthSyncRouteImport } from './routes/_auth/sync'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthOutboundRouteImport } from './routes/_auth/outbound'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthInventoryRouteImport } from './routes/_auth/inventory'
import { Route as AuthInboundRouteImport } from './routes/_auth/inbound'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthComplianceRouteImport } from './routes/_auth/compliance'
import { Route as AuthChannelsRouteImport } from './routes/_auth/channels'
import { Route as AuthAuditRouteImport } from './routes/_auth/audit'
import { Route as AuthOrdersIndexRouteImport } from './routes/_auth/orders/index'
import { Route as AuthProfileSecurityRouteImport } from './routes/_auth/profile/security'
import { Route as AuthOrdersOrderIdRouteImport } from './routes/_auth/orders/$orderId'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAdminRolePermissionsRouteImport } from './routes/_auth/admin/role-permissions'
import { Route as AuthAdminLockedAccountsRouteImport } from './routes/_auth/admin/locked-accounts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaEnrollRoute = MfaEnrollRouteImport.update({
  id: '/mfa/enroll',
  path: '/mfa/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa/challenge',
  path: '/mfa/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTenantsRoute = AuthTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSyncRoute = AuthSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOutboundRoute = AuthOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryRoute = AuthInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInboundRoute = AuthInboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthComplianceRoute = AuthComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChannelsRoute = AuthChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditRoute = AuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersIndexRoute = AuthOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileSecurityRoute = AuthProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersOrderIdRoute = AuthOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRolePermissionsRoute =
  AuthAdminRolePermissionsRouteImport.update({
    id: '/admin/role-permissions',
    path: '/admin/role-permissions',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAdminLockedAccountsRoute = AuthAdminLockedAccountsRouteImport.update({
  id: '/admin/locked-accounts',
  path: '/admin/locked-accounts',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthAuditRoute
  '/channels': typeof AuthChannelsRoute
  '/compliance': typeof AuthComplianceRoute
  '/dashboard': typeof AuthDashboardRoute
  '/inbound': typeof AuthInboundRoute
  '/inventory': typeof AuthInventoryRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/outbound': typeof AuthOutboundRoute
  '/settings': typeof AuthSettingsRoute
  '/sync': typeof AuthSyncRoute
  '/tenants': typeof AuthTenantsRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/admin/locked-accounts': typeof AuthAdminLockedAccountsRoute
  '/admin/role-permissions': typeof AuthAdminRolePermissionsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/profile/security': typeof AuthProfileSecurityRoute
  '/orders/': typeof AuthOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthAuditRoute
  '/channels': typeof AuthChannelsRoute
  '/compliance': typeof AuthComplianceRoute
  '/dashboard': typeof AuthDashboardRoute
  '/inbound': typeof AuthInboundRoute
  '/inventory': typeof AuthInventoryRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/outbound': typeof AuthOutboundRoute
  '/settings': typeof AuthSettingsRoute
  '/sync': typeof AuthSyncRoute
  '/tenants': typeof AuthTenantsRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/admin/locked-accounts': typeof AuthAdminLockedAccountsRoute
  '/admin/role-permissions': typeof AuthAdminRolePermissionsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/profile/security': typeof AuthProfileSecurityRoute
  '/orders': typeof AuthOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/audit': typeof AuthAuditRoute
  '/_auth/channels': typeof AuthChannelsRoute
  '/_auth/compliance': typeof AuthComplianceRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/inbound': typeof AuthInboundRoute
  '/_auth/inventory': typeof AuthInventoryRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/outbound': typeof AuthOutboundRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/sync': typeof AuthSyncRoute
  '/_auth/tenants': typeof AuthTenantsRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/_auth/admin/locked-accounts': typeof AuthAdminLockedAccountsRoute
  '/_auth/admin/role-permissions': typeof AuthAdminRolePermissionsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/_auth/profile/security': typeof AuthProfileSecurityRoute
  '/_auth/orders/': typeof AuthOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/audit'
    | '/channels'
    | '/compliance'
    | '/dashboard'
    | '/inbound'
    | '/inventory'
    | '/onboarding'
    | '/outbound'
    | '/settings'
    | '/sync'
    | '/tenants'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/admin/locked-accounts'
    | '/admin/role-permissions'
    | '/admin/users'
    | '/orders/$orderId'
    | '/profile/security'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/audit'
    | '/channels'
    | '/compliance'
    | '/dashboard'
    | '/inbound'
    | '/inventory'
    | '/onboarding'
    | '/outbound'
    | '/settings'
    | '/sync'
    | '/tenants'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/admin/locked-accounts'
    | '/admin/role-permissions'
    | '/admin/users'
    | '/orders/$orderId'
    | '/profile/security'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_auth/audit'
    | '/_auth/channels'
    | '/_auth/compliance'
    | '/_auth/dashboard'
    | '/_auth/inbound'
    | '/_auth/inventory'
    | '/_auth/onboarding'
    | '/_auth/outbound'
    | '/_auth/settings'
    | '/_auth/sync'
    | '/_auth/tenants'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/_auth/admin/locked-accounts'
    | '/_auth/admin/role-permissions'
    | '/_auth/admin/users'
    | '/_auth/orders/$orderId'
    | '/_auth/profile/security'
    | '/_auth/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  MfaEnrollRoute: typeof MfaEnrollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/enroll': {
      id: '/mfa/enroll'
      path: '/mfa/enroll'
      fullPath: '/mfa/enroll'
      preLoaderRoute: typeof MfaEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/challenge': {
      id: '/mfa/challenge'
      path: '/mfa/challenge'
      fullPath: '/mfa/challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/tenants': {
      id: '/_auth/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthTenantsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sync': {
      id: '/_auth/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AuthSyncRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/outbound': {
      id: '/_auth/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof AuthOutboundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory': {
      id: '/_auth/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthInventoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inbound': {
      id: '/_auth/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof AuthInboundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/compliance': {
      id: '/_auth/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthComplianceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/channels': {
      id: '/_auth/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthChannelsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit': {
      id: '/_auth/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthAuditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/': {
      id: '/_auth/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthOrdersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/security': {
      id: '/_auth/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AuthProfileSecurityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/$orderId': {
      id: '/_auth/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthOrdersOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/role-permissions': {
      id: '/_auth/admin/role-permissions'
      path: '/admin/role-permissions'
      fullPath: '/admin/role-permissions'
      preLoaderRoute: typeof AuthAdminRolePermissionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/locked-accounts': {
      id: '/_auth/admin/locked-accounts'
      path: '/admin/locked-accounts'
      fullPath: '/admin/locked-accounts'
      preLoaderRoute: typeof AuthAdminLockedAccountsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuditRoute: typeof AuthAuditRoute
  AuthChannelsRoute: typeof AuthChannelsRoute
  AuthComplianceRoute: typeof AuthComplianceRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthInboundRoute: typeof AuthInboundRoute
  AuthInventoryRoute: typeof AuthInventoryRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthOutboundRoute: typeof AuthOutboundRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSyncRoute: typeof AuthSyncRoute
  AuthTenantsRoute: typeof AuthTenantsRoute
  AuthAdminLockedAccountsRoute: typeof AuthAdminLockedAccountsRoute
  AuthAdminRolePermissionsRoute: typeof AuthAdminRolePermissionsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthOrdersOrderIdRoute: typeof AuthOrdersOrderIdRoute
  AuthProfileSecurityRoute: typeof AuthProfileSecurityRoute
  AuthOrdersIndexRoute: typeof AuthOrdersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuditRoute: AuthAuditRoute,
  AuthChannelsRoute: AuthChannelsRoute,
  AuthComplianceRoute: AuthComplianceRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthInboundRoute: AuthInboundRoute,
  AuthInventoryRoute: AuthInventoryRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthOutboundRoute: AuthOutboundRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSyncRoute: AuthSyncRoute,
  AuthTenantsRoute: AuthTenantsRoute,
  AuthAdminLockedAccountsRoute: AuthAdminLockedAccountsRoute,
  AuthAdminRolePermissionsRoute: AuthAdminRolePermissionsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthOrdersOrderIdRoute: AuthOrdersOrderIdRoute,
  AuthProfileSecurityRoute: AuthProfileSecurityRoute,
  AuthOrdersIndexRoute: AuthOrdersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  MfaEnrollRoute: MfaEnrollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
