/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTenantsRouteImport } from './routes/_auth/tenants'
import { Route as AuthSyncRouteImport } from './routes/_auth/sync'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthOutboundRouteImport } from './routes/_auth/outbound'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthInventoryRouteImport } from './routes/_auth/inventory'
import { Route as AuthInboundRouteImport } from './routes/_auth/inbound'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthChannelsRouteImport } from './routes/_auth/channels'
import { Route as AuthAuditRouteImport } from './routes/_auth/audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTenantsRoute = AuthTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSyncRoute = AuthSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOutboundRoute = AuthOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryRoute = AuthInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInboundRoute = AuthInboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChannelsRoute = AuthChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditRoute = AuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthAuditRoute
  '/channels': typeof AuthChannelsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/inbound': typeof AuthInboundRoute
  '/inventory': typeof AuthInventoryRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/outbound': typeof AuthOutboundRoute
  '/settings': typeof AuthSettingsRoute
  '/sync': typeof AuthSyncRoute
  '/tenants': typeof AuthTenantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthAuditRoute
  '/channels': typeof AuthChannelsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/inbound': typeof AuthInboundRoute
  '/inventory': typeof AuthInventoryRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/outbound': typeof AuthOutboundRoute
  '/settings': typeof AuthSettingsRoute
  '/sync': typeof AuthSyncRoute
  '/tenants': typeof AuthTenantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/audit': typeof AuthAuditRoute
  '/_auth/channels': typeof AuthChannelsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/inbound': typeof AuthInboundRoute
  '/_auth/inventory': typeof AuthInventoryRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/outbound': typeof AuthOutboundRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/sync': typeof AuthSyncRoute
  '/_auth/tenants': typeof AuthTenantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/channels'
    | '/dashboard'
    | '/inbound'
    | '/inventory'
    | '/onboarding'
    | '/outbound'
    | '/settings'
    | '/sync'
    | '/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/channels'
    | '/dashboard'
    | '/inbound'
    | '/inventory'
    | '/onboarding'
    | '/outbound'
    | '/settings'
    | '/sync'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/audit'
    | '/_auth/channels'
    | '/_auth/dashboard'
    | '/_auth/inbound'
    | '/_auth/inventory'
    | '/_auth/onboarding'
    | '/_auth/outbound'
    | '/_auth/settings'
    | '/_auth/sync'
    | '/_auth/tenants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/tenants': {
      id: '/_auth/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthTenantsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sync': {
      id: '/_auth/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AuthSyncRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/outbound': {
      id: '/_auth/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof AuthOutboundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory': {
      id: '/_auth/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthInventoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inbound': {
      id: '/_auth/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof AuthInboundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/channels': {
      id: '/_auth/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthChannelsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit': {
      id: '/_auth/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthAuditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuditRoute: typeof AuthAuditRoute
  AuthChannelsRoute: typeof AuthChannelsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthInboundRoute: typeof AuthInboundRoute
  AuthInventoryRoute: typeof AuthInventoryRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthOutboundRoute: typeof AuthOutboundRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSyncRoute: typeof AuthSyncRoute
  AuthTenantsRoute: typeof AuthTenantsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuditRoute: AuthAuditRoute,
  AuthChannelsRoute: AuthChannelsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthInboundRoute: AuthInboundRoute,
  AuthInventoryRoute: AuthInventoryRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthOutboundRoute: AuthOutboundRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSyncRoute: AuthSyncRoute,
  AuthTenantsRoute: AuthTenantsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
